/* Generated by Together */
package org.dejavu.activefx;

public class AfxException extends Exception {

	public AfxException(String desc) {
		super(desc);
	}
	public AfxException(String desc, Throwable cause) {
		super(desc,cause);
	}
}
