/* Generated by Together */
package org.dejavu.activefx;

import java.nio.ByteBuffer;
import java.nio.channels.SelectableChannel;

/**
 * The interface for handling Active FX events. Typically used by Active FX
 * clients to get request notifications.
 */
public interface AfxEventHandler {

	/**
	 * The Active FX connection had been open, and is ready for read/write
	 * request.
	 */
	void openCompleted();

	/**
	 * The Active FX connection is now closed.
	 */
	void closed();

	/**
	 * The previous read request is now completed, the supplied buffer is filled
	 * with data read in from the network.
	 *
	 * @param returnedBuffer The buffer given to the read command, which now
	 * contains the input data.
	 */
	void readCompleted(ByteBuffer returnedBuffer);

	/**
	 * The previous write request is completed.
	 */
	void writeCompleted();

	/**
	 * A new Active FX connection had been accepted and created.
	 *
	 * @param newConnection The new Active FX connection.
	 * @todo See if we could trim down to only one acceptCompleted.
	 */
	void acceptCompleted(AfxConnection newConnection);

	/**
	 * A new channel had been accepted
	 *
	 * @param newChannel The new SelectableChannel (i.e. SocketChannel)
	 * @todo See if we could trim down to only one acceptCompleted.
	 */
	void acceptCompleted(SelectableChannel newChannel);

	/**
	 * The previous open request failed.
	 *
	 * @param theCause Arbitrary cause of the failure
	 */
	void openFailed(String theCause);

	/**
	 * The previous read request had failed.
	 */
	void readFailed();

	/**
	 * The previous write request had failed.
	 */
	void writeFailed();
}
