/* Generated by Together */
package org.dejavu.activefx;

import java.nio.channels.SelectableChannel;

/**
 * Interface for handling reactor events.
 */
interface ReactorEventHandler {

	/**
	 * An accept event is detected by the reactor.
	 */
	void onAccept();

	/**
	 * A connect event is detected by the reactor.
	 * @throws java.lang.InterruptedException
	 */
	void onConnect() throws InterruptedException;

	/**
	 * A disconnect event is detected by the reactor.
	 * @throws java.lang.InterruptedException
	 */
	void onDisconnect() throws InterruptedException;

	/**
	 * A read event is detected by the reactor.
	 * @throws java.lang.InterruptedException
	 */
	void onRead() throws InterruptedException;

	/**
	 * A write event is detected by the reactor.
	 * @throws java.lang.InterruptedException
	 */
	void onWrite() throws InterruptedException;

	/**
	 * Retrieves the selectable channel associated with this reactor client.
	 *
	 * @return The requested selectable channel
	 */
	SelectableChannel getHandle();
}
