/* Generated by Together */

package org.dejavu.fsm;

/**
 * Interface for concrete FSM context to implement. 
 */
public interface FsmContext
{
	/**
	 * Retrieves the current state of the FSM context.
	 * @return The current state of this FSM context. Null if the current state
	 * is not known
	 */
	FsmState getCurrentState();

	/**
	 * Sets the current state of the context.
	 * @param newState The new state of this FSM context.
	 */
	void setCurrentState(FsmState newState);

	/**
	 * Retrieves the FSM domain in which this context lives.
	 * @return The containing FSM domain, not null.
	 */
	FsmDomain getFsmDomain();
}
