/* Generated by Together */

package org.dejavu.fsm;

/**
 * Abstract factory for instantiating FSM events. The design stipulates that each concrete event type will have its own concrete event factory extending this abstract factory.
 * @deprecated No longer used.
 */
public abstract class FsmEventFactory
{
}
