/* Generated by Together */

package org.dejavu.fsm;

/**
 * Interface for all concrete FSM events to implement. 
 */
public interface FsmEvent
{
	/**
	 * Gets the target context associated with this event. 
	 */
	FsmContext getContext();

	/**
	 * Gets the ID of the event. 
	 */
	int getId();

	/** @link dependency */
    /*# FsmContext lnkFsmContext; */
}
