/* Generated by Together */

package com.mitel.icp;

/**
 * Used for getting the ICP service loaded and started.
 */
public class IcpService
{
	/**
	 * Acquires the IcpService singleton instance. 
	 * This will create the singleton instance when first invoked.
	 * 
	 * @return The singleton instance.
	 */
	public static IcpService getInstance()
	{
		return s_Singleton;
	}
	
	/**
	 * Singleton instance, which will be created when getInstance() is first called.
	 * @supplierCardinality 1
	 */
	protected static final IcpService s_Singleton = new IcpService(true);

	/**
	 * Initialization constructor. Gets the ICP services started.
	 * @param defaultSetting If true then the ICP service will instantiate some default ICP types. Otherwise this constructor does nothing.
	 */
	@SuppressWarnings("ResultOfObjectAllocationIgnored")
	protected IcpService(boolean defaultSetting)
	{
		if(defaultSetting)
		{
			// Creates all ICP types

			// SX200ICP
			new IcpApi200("SX200ICP");

			// MN3300ICP
			new IcpApi3300_r60(ICP_TYPE_3300ICP_HEAVY, IcpTypeInfo.IcpClass.MCD_MxeExt);
			new IcpApi3300_r60(ICP_TYPE_3300ICP_LITE, IcpTypeInfo.IcpClass.MCD_Mxe);
			new IcpApi3300_r60(ICP_TYPE_3300ICP, IcpTypeInfo.IcpClass.MCD_MxeExt);
			new IcpApi3600();
			new IcpApi3300_LicsR80(ICP_TYPE_3300LiCS, IcpTypeInfo.IcpClass.MCD_MxeServer);
			new IcpApi3300_LicsR80(ICP_TYPE_MCD, IcpTypeInfo.IcpClass.MCD_Server);
			new IcpApi3300_LicsR80(ICP_TYPE_MCD_MBG, IcpTypeInfo.IcpClass.MCD_MBG);
		}
	}

	/**
	 * 3600 (NCI thing)
	 */
	public static final String ICP_TYPE_3600 = "3600";
	/**
	 * MCD hiding behind MBG
	 */
	public static final String ICP_TYPE_MCD_MBG = "MCD_MBG";
	/**
	 * 3300LiCS (Linux call servers)
	 */
	public static final String ICP_TYPE_MCD = "MCD";
	/**
	 * 3300LiCS (Linux call servers)
	 */
	public static final String ICP_TYPE_3300LiCS = "3300LICS";
	/**
	 * 3300ICP (typically MXe heavies, i.e. have separate E2T cards)
	 */
	public static final String ICP_TYPE_3300ICP = "3300ICP";
	/**
	 * 3300ICP (MXe heavies, i.e. have separate E2T cards)
	 */
	public static final String ICP_TYPE_3300ICP_HEAVY = "3300ICP.heavy";
	/**
	 * 3300ICP (MXe light, i.e. no E2T cards)
	 */
	public static final String ICP_TYPE_3300ICP_LITE = "3300ICP.lite";
}

