/* Generated by Together */

package org.dejavu.fsm;

/**
 * Interface for FSM actions to implement. This covers transition actions, guard, entry function, and exit function. 
 */
public interface FsmAction
{
	/**
	 * Handles an event.
	 * @param event The event to be handled
	 * @return True if the event was handled, false otherwise.
	 */
	boolean handleEvent(FsmEvent event);
}
