/* Generated by Together */

package org.dejavu.fsm;

import org.dejavu.util.DjvLogMsg.Category;
import org.dejavu.util.DjvSystem;
import java.util.HashMap;
import java.util.Map;

/**
 * Class utilities providing some value-added functionality for the FSM framework. 
 */
public class FsmUtilities
{
	private final static Map<String, Integer> m_StateIdMap = new HashMap<String, Integer>();
	private static int m_StateIdCount = 0;
	static final int INVALID_STATE_ID = -1;

	/**
	 * Given a state name, returns a unique ID. 
	 * @param stateName The name of the desired state.
	 * @return The ID of the desired state.
	 */
	public static int registerState(String stateName)
	{
		Integer stateId = null;
		synchronized(m_StateIdMap)
		{
			stateId = m_StateIdMap.get(stateName);
			if(null == stateId)
			{
				int newCount = m_StateIdCount++;
				m_StateIdMap.put(stateName, Integer.valueOf(newCount));
				return newCount;
			}
			else
			{
				DjvSystem.logWarning(Category.DESIGN,
					"State name collision of " + stateName);
			}
		}
		return stateId.intValue();
	}
}
