/* Generated by Together */

package com.mitel.activefx;
import java.nio.channels.SelectableChannel;

/**
 * Interface for handling reactor events.
 */
interface ReactorEventHandler
{
	/**
	 * An accept event is detected by the reactor.
	 */
	void onAccept();

	/**
	 * A connect event is detected by the reactor.
	 */
	void onConnect();

	/**
	 * A disconnect event is detected by the reactor.
	 */
	void onDisconnect();

	/**
	 * A read event is detected by the reactor.
	 */
	void onRead();

	/**
	 * A write event is detected by the reactor.
	 */
	void onWrite();

	/**
	 * Retrieves the selectable channel associated with this reactor client.
	 * @return The requested selectable channel
	 */
	SelectableChannel getHandle();
}
