/* Generated by Together */

package com.mitel.mifsm;

/**
 * Custom exception for use with the FSM framework.
 * @author haiv
 */
public class FsmException extends Exception
{
	private static final long serialVersionUID = 1L;
	/**
	 * Creates a new instance of the FSM exception.
	 * @param desc An arbitrary text string describing the exception.
	 */
	public FsmException(String desc)
	{
        super(desc);
	}
}
