/*
 * AboutDialog.java
 *
 * Created on November 15, 2003, 4:23 PM
 */

package com.mitel.guiutil;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Hai Vu
 */
public class AboutDialog extends JDialog 
{
	private static final long serialVersionUID = 1L;
    
	/** Creates new form AboutDialog
	 * @param info Information to be displayed in the dialog.
	 * @param parent The parent frame of this dialog.
	 */
    public AboutDialog(AboutInformation info, Frame parent) 
	{
        super(parent, true);
		m_Info = info;
		setTitle(m_Info.m_Title);
		initComponents();

		MiGuiUtil.registerKeyAction(getRootPane(), KeyEvent.VK_ESCAPE, new AbstractAction()
		{
			private static final long serialVersionUID = 1L;
			@Override
			public void actionPerformed(ActionEvent e)
			{
				dispose();
			}
		});
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        animatedPanel = new AboutPanel(m_Info);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        animatedPanel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(animatedPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


	private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
	{//GEN-HEADEREND:event_formWindowOpened
		start();
	}//GEN-LAST:event_formWindowOpened
   
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) 
	{
		MiLookAndFeel.setCurrentLookAndFeel(MiLookAndFeel.LAF_SUBSTANCE_CREME_COFFEE);
		SwingUtilities.invokeLater(new Runnable()
		{
			public void run()
			{
				JFrame parentFrame = new JFrame();
				List<String> strs = new ArrayList<String>();
				strs.add(0, "A Deja Vu Production");
				strs.add(1, "Created by Hai Vu");
				strs.add(2, "For Mitel's ICP family of fine products");
				strs.add(3, "Powered by Java");
				strs.add(4, "Developed with NetBeans (www.netbeans.org)");
				strs.add(5, "Made in Canada");

				AboutInformation info = new AboutInformation("MiDAS - About", "images/midas.gif", 
					new Dimension(400, 280), strs);

				MiGuiUtil.centerAndMakeVisible(new AboutDialog (info, parentFrame), parentFrame);
				parentFrame.dispose();
			}
		});
    }
    
    public void start() 
    {
		((AboutPanel)(animatedPanel)).start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animatedPanel;
    // End of variables declaration//GEN-END:variables
	          
      
	private int m_numberOfScenes = 50;
	private Thread m_Thread = null;
	
	private AboutInformation m_Info;

	private Frame m_ParentFrame;
}
