/*
 * PasswordDialog.java
 *
 * Created on June 3, 2005, 4:15 PM
 */

package org.dejavu.guiutil;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.SwingUtilities;

/**
 * Implements a password entry dialog.
 * @author  haiv
 */
public class PasswordDialog extends javax.swing.JDialog
{
	private static final long serialVersionUID = 1L;
	private final Frame m_Frame;
	
	/** Creates new form PasswordDialog
	 * @param parent The parent frame to this dialog.
	 * @param listener Listener interface for reporting user entry upon completion.
	 */
	public PasswordDialog(java.awt.Frame parent, PasswordListener listener)
	{
		super(parent, true);
		m_Frame = parent;
		m_Listener = listener;
		initComponents();
		initDialog();
		
		DjvGuiUtil.registerKeyAction(getRootPane(), KeyEvent.VK_ESCAPE, new AbstractAction()
		{
			private static final long serialVersionUID = 1L;
			@Override
			public void actionPerformed(ActionEvent e)
			{
				cancel();
			}
		});
	}
	
	private void initDialog()
	{
		SwingUtilities.invokeLater(new Runnable()
		{
			@Override
			public void run()
			{
				pack();
				int x = m_Frame.getX() + (m_Frame.getWidth() - getWidth())/2;
				int y = m_Frame.getY() + (m_Frame.getHeight() - getHeight())/2;

				if(0 > x)
					x = 0;
				if(0 > y)
					y = 0;

				setLocation(x, y);
				setVisible(true);
			}
		});
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oldPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/dejavu/guiutil/GeneralGui"); // NOI18N
        setTitle(bundle.getString("passwordEntryLabel")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(bundle.getString("oldPasswordLabel")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel1, gridBagConstraints);

        oldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordActionPerformed(evt);
            }
        });
        oldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                oldPasswordFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(oldPassword, gridBagConstraints);

        jLabel2.setText(bundle.getString("newPasswordLabel")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel2, gridBagConstraints);

        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        newPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(newPassword, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel2.setOpaque(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        okButton.setText(bundle.getString("okLabel")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        cancelButton.setText(bundle.getString("cancelLabel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void oldPasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_oldPasswordActionPerformed
	{//GEN-HEADEREND:event_oldPasswordActionPerformed
		newPassword.requestFocusInWindow();
	}//GEN-LAST:event_oldPasswordActionPerformed

	private void newPasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newPasswordActionPerformed
	{//GEN-HEADEREND:event_newPasswordActionPerformed
		okButton.requestFocusInWindow();
	}//GEN-LAST:event_newPasswordActionPerformed

	private void newPasswordFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_newPasswordFocusGained
	{//GEN-HEADEREND:event_newPasswordFocusGained
		newPassword.selectAll();
	}//GEN-LAST:event_newPasswordFocusGained

	private void oldPasswordFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_oldPasswordFocusGained
	{//GEN-HEADEREND:event_oldPasswordFocusGained
		oldPassword.selectAll();
	}//GEN-LAST:event_oldPasswordFocusGained

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
	{//GEN-HEADEREND:event_cancelButtonActionPerformed
		cancel();
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
	{//GEN-HEADEREND:event_formWindowClosing
		cancel();
	}//GEN-LAST:event_formWindowClosing

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
	{//GEN-HEADEREND:event_okButtonActionPerformed
		commit();
	}//GEN-LAST:event_okButtonActionPerformed
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		DjvLookAndFeel.setCurrentLookAndFeel(DjvLookAndFeel.LAF_SUBSTANCE_CREME_COFFEE);
		SwingUtilities.invokeLater(() -> {
			final Frame frame = new javax.swing.JFrame();
			new PasswordDialog(frame, new PasswordDialog.PasswordListener()
			{
				@Override
				public void commit(String oldPassword, String newPassword, PasswordDialog dialog)
				{
					frame.dispose();
				}
				
				@Override
				public void cancel(PasswordDialog dialog)
				{
					frame.dispose();
				}
			});
		});
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField oldPassword;
    // End of variables declaration//GEN-END:variables

	public interface PasswordListener
	{
		public void commit(String oldPassword, String newPassword, PasswordDialog dialog);
		public void cancel(PasswordDialog dialog);
	}

	private final PasswordListener m_Listener;

	private void commit()
	{
		if(null != m_Listener)
			m_Listener.commit(String.valueOf(oldPassword.getPassword()), String.valueOf(newPassword.getPassword()), this);
	}

	private void cancel()
	{
		if(null != m_Listener)
			m_Listener.cancel(this);
	}
}
